/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DayPlanner {
        /**
          * The day of the week this slot represents, e.g. "Monday"
         */
        "dayLabel": string;
        /**
          * Thumbnail image of the assigned recipe, if any
         */
        "imageUrl": string;
        /**
          * Title of the recipe assigned to this day, if any
         */
        "recipeTitle": string;
    }
    interface RatingStar {
        /**
          * Maximum number of stars to display
          * @default 5
         */
        "maxRating": number;
        /**
          * Current rating value, e.g. 4.5
          * @default 0
         */
        "rating": number;
        /**
          * If true, stars are display-only and not clickable
          * @default false
         */
        "readonly": boolean;
    }
    interface RecipeCard {
        /**
          * Category of the recipe, e.g. "Dessert", "Seafood"
         */
        "category": string;
        /**
          * URL of the recipe's image (thumbnail)
         */
        "imageUrl": string;
        /**
          * Whether this recipe is currently marked as favorite
          * @default false
         */
        "isFavorite": boolean;
        /**
          * The title of the recipe
         */
        "recipeTitle": string;
    }
}
export interface DayPlannerCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLDayPlannerElement;
}
export interface RatingStarCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRatingStarElement;
}
export interface RecipeCardCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRecipeCardElement;
}
declare global {
    interface HTMLDayPlannerElementEventMap {
        "mealRemoved": { dayLabel: string };
    }
    interface HTMLDayPlannerElement extends Components.DayPlanner, HTMLStencilElement {
        addEventListener<K extends keyof HTMLDayPlannerElementEventMap>(type: K, listener: (this: HTMLDayPlannerElement, ev: DayPlannerCustomEvent<HTMLDayPlannerElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLDayPlannerElementEventMap>(type: K, listener: (this: HTMLDayPlannerElement, ev: DayPlannerCustomEvent<HTMLDayPlannerElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLDayPlannerElement: {
        prototype: HTMLDayPlannerElement;
        new (): HTMLDayPlannerElement;
    };
    interface HTMLRatingStarElementEventMap {
        "ratingChanged": { rating: number };
    }
    interface HTMLRatingStarElement extends Components.RatingStar, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRatingStarElementEventMap>(type: K, listener: (this: HTMLRatingStarElement, ev: RatingStarCustomEvent<HTMLRatingStarElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRatingStarElementEventMap>(type: K, listener: (this: HTMLRatingStarElement, ev: RatingStarCustomEvent<HTMLRatingStarElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRatingStarElement: {
        prototype: HTMLRatingStarElement;
        new (): HTMLRatingStarElement;
    };
    interface HTMLRecipeCardElementEventMap {
        "favoriteToggled": { recipeTitle: string };
    }
    interface HTMLRecipeCardElement extends Components.RecipeCard, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRecipeCardElementEventMap>(type: K, listener: (this: HTMLRecipeCardElement, ev: RecipeCardCustomEvent<HTMLRecipeCardElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRecipeCardElementEventMap>(type: K, listener: (this: HTMLRecipeCardElement, ev: RecipeCardCustomEvent<HTMLRecipeCardElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRecipeCardElement: {
        prototype: HTMLRecipeCardElement;
        new (): HTMLRecipeCardElement;
    };
    interface HTMLElementTagNameMap {
        "day-planner": HTMLDayPlannerElement;
        "rating-star": HTMLRatingStarElement;
        "recipe-card": HTMLRecipeCardElement;
    }
}
declare namespace LocalJSX {
    interface DayPlanner {
        /**
          * The day of the week this slot represents, e.g. "Monday"
         */
        "dayLabel"?: string;
        /**
          * Thumbnail image of the assigned recipe, if any
         */
        "imageUrl"?: string;
        /**
          * Emitted when the user clicks "remove" on an assigned meal
         */
        "onMealRemoved"?: (event: DayPlannerCustomEvent<{ dayLabel: string }>) => void;
        /**
          * Title of the recipe assigned to this day, if any
         */
        "recipeTitle"?: string;
    }
    interface RatingStar {
        /**
          * Maximum number of stars to display
          * @default 5
         */
        "maxRating"?: number;
        /**
          * Emitted when the user clicks a star (only if readonly is false)
         */
        "onRatingChanged"?: (event: RatingStarCustomEvent<{ rating: number }>) => void;
        /**
          * Current rating value, e.g. 4.5
          * @default 0
         */
        "rating"?: number;
        /**
          * If true, stars are display-only and not clickable
          * @default false
         */
        "readonly"?: boolean;
    }
    interface RecipeCard {
        /**
          * Category of the recipe, e.g. "Dessert", "Seafood"
         */
        "category"?: string;
        /**
          * URL of the recipe's image (thumbnail)
         */
        "imageUrl"?: string;
        /**
          * Whether this recipe is currently marked as favorite
          * @default false
         */
        "isFavorite"?: boolean;
        "onFavoriteToggled"?: (event: RecipeCardCustomEvent<{ recipeTitle: string }>) => void;
        /**
          * The title of the recipe
         */
        "recipeTitle"?: string;
    }

    interface DayPlannerAttributes {
        "dayLabel": string;
        "recipeTitle": string;
        "imageUrl": string;
    }
    interface RatingStarAttributes {
        "rating": number;
        "maxRating": number;
        "readonly": boolean;
    }
    interface RecipeCardAttributes {
        "recipeTitle": string;
        "imageUrl": string;
        "category": string;
        "isFavorite": boolean;
    }

    interface IntrinsicElements {
        "day-planner": Omit<DayPlanner, keyof DayPlannerAttributes> & { [K in keyof DayPlanner & keyof DayPlannerAttributes]?: DayPlanner[K] } & { [K in keyof DayPlanner & keyof DayPlannerAttributes as `attr:${K}`]?: DayPlannerAttributes[K] } & { [K in keyof DayPlanner & keyof DayPlannerAttributes as `prop:${K}`]?: DayPlanner[K] };
        "rating-star": Omit<RatingStar, keyof RatingStarAttributes> & { [K in keyof RatingStar & keyof RatingStarAttributes]?: RatingStar[K] } & { [K in keyof RatingStar & keyof RatingStarAttributes as `attr:${K}`]?: RatingStarAttributes[K] } & { [K in keyof RatingStar & keyof RatingStarAttributes as `prop:${K}`]?: RatingStar[K] };
        "recipe-card": Omit<RecipeCard, keyof RecipeCardAttributes> & { [K in keyof RecipeCard & keyof RecipeCardAttributes]?: RecipeCard[K] } & { [K in keyof RecipeCard & keyof RecipeCardAttributes as `attr:${K}`]?: RecipeCardAttributes[K] } & { [K in keyof RecipeCard & keyof RecipeCardAttributes as `prop:${K}`]?: RecipeCard[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "day-planner": LocalJSX.IntrinsicElements["day-planner"] & JSXBase.HTMLAttributes<HTMLDayPlannerElement>;
            "rating-star": LocalJSX.IntrinsicElements["rating-star"] & JSXBase.HTMLAttributes<HTMLRatingStarElement>;
            "recipe-card": LocalJSX.IntrinsicElements["recipe-card"] & JSXBase.HTMLAttributes<HTMLRecipeCardElement>;
        }
    }
}
